server:
  port: 8082


spring:
  application:
    name: Hotel-service   
    
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  config:
    import: optional:configserver:http://localhost:8085 
#   It is used when, we need to externalize properties to dev- spring.profile.active: dev
  profiles:
    active: dev
    
#This is not needed now, beacause, we are using config.import to externalise properties to github
          
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka